export const GROUPCHAT = [
  { code: "BDG", name: "Bandung", link: "https://t.me/+ZVly78dQmFFjNmFl" },
  { code: "BYMS", name: "Banyumas", link: "https://t.me/+HgKXB7O0LR40NTE1" },
  { code: "CRBN", name: "Cirebon", link: "https://t.me/+f8XqjCGxH8I0NGM1" },
  { code: "JBDT", name: "Jabodetabek", link: "https://t.me/+aWxKsjQpBRVmMmRl" },
  { code: "JBR", name: "Jember", link: "https://t.me/+EW5oOJHntL42OGVl" },
  { code: "KLMT", name: "Kalimantan", link: "https://t.me/+wW0oPCExT-w2NjNl" },
  { code: "KDR", name: "Kediri", link: "https://t.me/+8oeFsEI0IqYxODA1" },
  { code: "LMG", name: "Lamongan", link: "https://t.me/+wq4WzTKrPWE2NWY1" },
  { code: "MDN", name: "Madiun", link: "https://t.me/+psBFLasw6PdiNzJl" },
  { code: "MDR", name: "Madura", link: "https://t.me/+0FCiwEeemyA3ZWM1" },
  { code: "MLG", name: "Malang", link: "https://t.me/+sT166xBYiMw5NDZl" },
  { code: "PPBL", name: "Probolinggo", link: "https://t.me/+tjJJe2-gjxE0YmQ1" },
  { code: "PNRG", name: "Ponorogo", link: "https://t.me/+Ki-s8RKQC703ZDY1" },
  { code: "SMG", name: "Semarang", link: "https://t.me/+Fwd3l6mkHn4zYzQ1" },
  { code: "SLWS", name: "Sulawesi", link: "https://t.me/+PI8H5xfJwacxNTg1" },
  { code: "SMTR", name: "Sumatra", link: "https://t.me/+FPt7-LB2-NJjNzY1" },
  { code: "SBY", name: "Surabaya", link: "https://t.me/+KYJRDjsDTJgzOTBl" },
  { code: "YGY", name: "Yogyakarta", link: "https://t.me/+s5gQP_qQSRZmZWVl" },
];
