import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import NextTopLoader from "nextjs-toploader";

const font = Ubuntu({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Pendaftaran Olmat Uinsa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <NextTopLoader
          color="#7FC7D9"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          zIndex={100000}
          showSpinner={true}
          easing="ease"
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
